# Generated by Django 3.0.4 on 2020-04-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eHostelApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='no_due_receipt',
        ),
        migrations.AlterField(
            model_name='room',
            name='h_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roommate',
            name='student_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student1', to='eHostelApp.Student'),
        ),
        migrations.AlterField(
            model_name='roommate',
            name='student_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student2', to='eHostelApp.Student'),
        ),
    ]
